AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Slopes Programming API
Globals:

  Function:
    Timeout: 3
    CodeUri: src/functions
  Api:
    Domain:
      DomainName: api.slopesprogramming.com
      CertificateArn: arn:aws:acm:us-west-2:636903234937:certificate/0a891046-a055-416d-a747-3da6e6bdef36

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: "default"
      Name: slopes-programming-api
      CacheClusterEnabled: True
      CacheClusterSize: '1.6'
      Cors:
        AllowMethods: "'OPTIONS,POST,GET,PUT,DELETE'"
        AllowCredentials: False
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              AllowHeaders: "'*'"
              AllowOrigin: "'*'"
              AllowMethods: "'OPTIONS,POST,GET,PUT,DELETE'"
  GetAllCompanies:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: company/app.get
      Runtime: nodejs12.x
      Role: arn:aws:iam::636903234937:role/SlopesProgrammingLambdaRole
      Events:
        GetCompaanies:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /companies
            Method: GET
            RestApiId:
              Ref: ApiGatewayApi
